# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: email_validator
  version: 2.3.0
source:
  url: https://pypi.org/packages/source/e/email-validator/email_validator-2.3.0.tar.gz
  sha256: 9fc05c37f2f6cf439ff414f8fc46d917929974a82244c20eb10231ba60c54426
build:
  noarch: generic
  number: 0
  string: hd8ed1ab_0
requirements:
  run:
    - email-validator >=2.3.0,<2.3.1.0a0
  build: []
test:
  imports:
    - email_validator
  commands:
    - email_validator blah@blah.com
about:
  home: https://github.com/JoshData/python-email-validator
  summary: A robust email address syntax and deliverability validation library.
  license: Unlicense
  license_file: LICENSE
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator
extra:
  feedstock-name: email-validator
  recipe-maintainers:
    - pmlandwehr
    - xylar
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250826.2.1
  remote_url: https://github.com/conda-forge/email-validator-feedstock
  sha: 06219c0bf3915c9d60886b12b1e55d764e436981
