# This file created by conda-build 26.1.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Feb  4 16:39:42 2026
# ------------------------------------------------

package:
  name: pyyaml
  version: 6.0.3
source:
  url: https://pypi.org/packages/source/P/PyYAML/pyyaml-6.0.3.tar.gz
  sha256: d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
build:
  number: '1'
  track_features: null
  string: py312h04c11ed_1
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h322ffc5_4
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_4
    - clang 19.1.7 default_h1323312_7
    - clang-19 19.1.7 default_hd70426c_7
    - clang_impl_osx-64 19.1.7 default_ha1a018a_7
    - clang_impl_osx-arm64 19.1.7 h4c5f930_31
    - clang_osx-arm64 19.1.7 h877a2d5_31
    - clangxx 19.1.7 default_h9089c59_7
    - clangxx_impl_osx-64 19.1.7 default_ha1a018a_7
    - clangxx_impl_osx-arm64 19.1.7 ha2d6da0_31
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - cross-python_osx-arm64 3.12 54_cpython
    - crossenv 1.5.0 pyhcf101f3_3
    - cython 3.2.4 py312h84c01df_0
    - ld64 956.6 llvm19_1_hc3792c1_4
    - ld64_osx-64 956.6 llvm19_1_hcae3351_4
    - ld64_osx-arm64 956.6 llvm19_1_h46d26d2_4
    - libclang-cpp19.1 19.1.7 default_hd70426c_7
    - libcxx 21.1.8 h3d58e20_1
    - libcxx-devel 19.1.7 h7c275be_2
    - libcxx-headers 19.1.7 h707e725_2
    - libexpat 2.7.3 heffb93a_0
    - libffi 3.5.2 hd1f9c09_0
    - libiconv 1.18 h57a12c2_2
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.2 h11316ed_0
    - libsigtool 0.1.3 hc0f2934_0
    - libsqlite 3.51.2 hb99441e_0
    - libxml2 2.15.1 h745d5cb_1
    - libxml2-16 2.15.1 hd57b93d_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.8 h472b3d1_0
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - lz4-c 1.10.0 h240833e_1
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_6
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.1 hb6871ef_1
    - popt 1.19 h2d2823b_0
    - python 3.12.12 h74c2667_2_cpython
    - python_abi 3.12 8_cp312
    - readline 8.3 h68b038d_0
    - rsync 3.4.1 hf2bfba0_2
    - sdkroot_env_osx-arm64 26.0 ha3f98da_6
    - sed 4.9 hf9b2955_0
    - sigtool-codesign 0.1.3 hc0f2934_0
    - tapi 1600.0.11.8 h8d8e812_0
    - tk 8.6.13 h7142dee_3
    - tzdata 2025c hc9c84f9_1
    - xxhash 0.8.3 h13e91ac_0
    - zstd 1.5.7 h3eecb57_6
  host:
    - bzip2 1.0.8 hd037594_8
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cython 3.2.4 py312hedd66cf_0
    - icu 78.2 h38cb7af_0
    - libcxx 21.1.8 hf598326_1
    - libexpat 2.7.3 haf25636_0
    - libffi 3.5.2 hcf2aa1b_0
    - liblzma 5.8.2 h8088a28_0
    - libsqlite 3.51.2 h1ae2325_0
    - libzlib 1.3.1 h8359307_2
    - ncurses 6.5 h5e97a16_3
    - openssl 3.6.1 hd24854e_1
    - packaging 26.0 pyhcf101f3_0
    - pip 26.0 pyh8b19718_0
    - python 3.12.12 h18782d2_2_cpython
    - python_abi 3.12 8_cp312
    - readline 8.3 h46df422_0
    - setuptools 80.10.2 pyh332efcf_0
    - tk 8.6.13 h010d191_3
    - tzdata 2025c hc9c84f9_1
    - wheel 0.46.3 pyhd8ed1ab_0
    - yaml 0.2.5 h925e9cb_3
  run:
    - __osx >=11.0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
    - yaml >=0.2.5,<0.3.0a0
test:
  imports:
    - _yaml
    - yaml
  commands:
    - pip check
  requires:
    - pip
about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  dev_url: https://github.com/yaml/pyyaml
  doc_url: http://pyyaml.org/wiki/PyYAML
extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260204.2.1
  remote_url: https://github.com/conda-forge/pyyaml-feedstock
  sha: c1f16949f0edec6fd6bf694330bec45716aad0f2
